### ISSUE TITLE
fails if first coverage has no Identifier

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs11#21]
The wcs:DescribeCoverage_MinimalRequest doesn't work if the first coverage has no identifier (which is legal, and used to indicate a theme hierarchy).  What seems to be happening is that the identifier of the first coverage (which in this case is undefined) is assigned to the $identifier1 variable, and that variable is blindly used in the DescribeCoverage request on the assumption that it's actually the name of a coverage.  So the following request gets sent:

https://demo.cubewerx.com/cubewerx/cubeserv/simple?DATASTORE=Foundation&&service=WCS&request=DescribeCoverage&version=1.1.1&identifiers=

This request is illegal, since at least one coverage needs to be specified by the identifiers parameter.

**Comment by pomakis** [comment]
This is also true for the wcs:DescribeCoverage_MissingVersion test (and probably others).

**Comment by dstenger** [comment]
Thank you for reporting the issue. We will do further investigation.

**Comment by dstenger** [comment]
We have created a fix for this issue which is provided by following pull request: #23.
The pull request will be merged into master branch when the next release is created (if testing of the fix is successful).

Please note that wcs:DescribeCoverage_MissingVersion is still failing as now a DescribeCoverage response is returned instead of an exception (but identifier problem is solved).

Also, the test suite needs more time to be executed as more test are applied.

**Comment by dstenger** [comment]
The pull request was merged into the master branch and will be part of the upcoming release.
