### ISSUE TITLE
Test wcs:GetCapabilities_Sections_Bogus - Specification is unclear about validation of values

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs11#49]
Table 1 of specification (OGC 07-067r2, page 10) states in footnote "a": "Server shall check that each value received is an allowed value."

However, specification does not describe what happens if the value is not allowed. There is no hint that an exception must be returned.

Thus, test might be erroneous.

**Comment by pomakis** [comment]
OGC 07-067r2 section 8.3.6 states:

"When a WCS server encounters an error while performing a GetCapabilities operation, it shall return an exception report message as specified in Clause 8 of [OGC 06-121r3]. The allowed exception codes shall include those listed in Table 8 of Subclause 7.4.1 of [OGC 06-121r3] when the updateSequence parameter is implemented by the server."

I think that last part, i.e., "when the updateSequence parameter is implemented by the server", isn't supposed to be there, since it makes no sense in the contect of that paragraph.  Anyways, the referred-to Table 8 of OGC 06-121r3 states that an exceptionCode value of "InvalidParameterValue" is for when the "operation request contains an invalid parameter value", and further states that the value "locator" should be the "name of parameter with invalid value".
 
So it's pretty clear here (and elsewhere in the specification), that the corrent
 response to a request with a parameter with an invalid value is an OWS Common 1
.1.0 exception report with an exception code of "InvalidParameterValue".

**Comment by greatzzk** [comment]
@dstenger @pomakis 
Thanks for creating the issue and the useful input. We've updated our implementation per comment.

**Comment by dstenger** [comment]
So, all questions should be clarified and the test implementation is correct.
