### ISSUE TITLE
wcs 1.1.1 compliance test getcapabilities issue

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs11#57]
based on the log, the te2 is testing with url like:
![image](https://user-images.githubusercontent.com/11200872/67515707-10242200-f654-11e9-9abd-c2d51988db11.png)
this is not right. the "version" parameter should be changed to "acceptversions".
reason:
![image](https://user-images.githubusercontent.com/11200872/67515807-3ea1fd00-f654-11e9-81bb-4ed7883e5afb.png)

**Comment by keshav-nangare** [comment]
According to documentation the GetCapabilities test should use AcceptVersions parameter instead of version. There are few GetCapabilities tests that are using acceptversions parameter and remaining are using the version parameter.

Also I saw the other test implementation as below:

Currently `GetCoverage`  test request using version parameter:
![image](https://user-images.githubusercontent.com/14732650/68651583-b4133600-054d-11ea-8038-f880a7c2ecad.png)

So, the changes should be done only for all GetCapabilities test.

**Comment by greatzzk** [comment]
@keshav-nangare 
Yes I agree. this issue was created for 1.1.1 getcapabilities only. thanks
